=== Sarsum/TINF23CS-kauma-tests/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://raw.githubusercontent.com/sarsum/TINF23CS-kauma-tests/refs/heads/main/schema.json",
  "title": "Test Vectors",
  "description": "Test Vector including input and expected result to test the kauma application",
  "additionalProperties": false,
  "properties": {
    "title": { "type": "string" },
    "description": { "type": "string" },
    "authors": { "type": "array", "items": { "type": "string" } },
    "testcases": {
      "type": "object",
      "minProperties": 1,
      "description": "Map of testcase name -> testcase",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "action": { "type": "string" },
          "arguments": {
            "type": "object"
          }
        },
        "required": ["action", "arguments"]
      }
    },
    "expectedResults": {
        "type": "object",
        "properties": {
            "responses": {
                "minProperties": 1,
                "description": "Results of testcases. Sometimes for each testcase a result, sometimes one result computed by multiple actions.",
                "additionalProperties": {
                  "type": ["object", "null"]
                }
            }
        }
    }
  },
  "required": ["title", "description", "testcases", "expectedResults"]
}

=== Sarsum/TINF23CS-kauma-tests/tests/04_action_rsa_factor_01.json
{
    "title": "rsa_factor large testcase from generator",
    "description": "small synthetic testcase with shared primes for batch GCD",
    "authors": ["Sarsum"],
    "testcases": {
        "001": {
            "action": "rsa_factor",
            "arguments": {
                "moduli": [
                    147406291,
                    98834707,
                    150128791,
                    225454147,
                    135775051,
                    179848771,
                    82203497,
                    231469471,
                    123120709,
                    111769597,
                    184279741,
                    158051077,
                    151045793,
                    162513569,
                    146871607,
                    101685097,
                    127978259,
                    124508849,
                    152167487,
                    125642977
                ]
            }
        }
    },
    "expectedResults": {
        "001": {
            "factored_moduli": [
                [
                    9649,
                    10243
                ],
                [
                    9649,
                    15559
                ],
                [
                    10009,
                    12301
                ],
                [
                    10009,
                    12553
                ]
            ]
        }
    }
}

=== Sarsum/TINF23CS-kauma-tests/tests/03_action_gfpoly_powmod_edgecases.json
{
    "title": "Edgecase with exp 0 and modulus 1",
    "description": "Exp-loop is not being run due to exp being run but modulus needs to be run at least once since being one",
    "testcases": {
        "edge": {
            "action": "gfpoly_powmod",
            "arguments": {
                "B": [
                    "gAAAAAAAAAAAAAAAAAAAAA=="
                ],
                "M": [
                    "gAAAAAAAAAAAAAAAAAAAAA=="
                ],
                "e": 0,
                "poly": "p1"
            }
        }
    },
    "expectedResults": {
        "edge": {
            "Z": [
                "AAAAAAAAAAAAAAAAAAAAAA=="
            ]
        }
    }
}

=== Sarsum/TINF23CS-kauma-tests/tests/padding_oracle.json
{
  "title": "Action: padding_oracle",
  "description": "Tests for testing the padding_oracle action. As well as some current invalid actions.",
  "testcases": {
    "test1": {
      "action": "padding_oracle",
      "arguments": {
        "hostname": "localhost",
        "port": 18652,
        "key_id": 1324,
        "iv": "dx9PBs7v4YSycOTbTnp8QQ==",
        "ciphertext": "3hUW5sEmIbldRORfj5l2jg=="
      }
    },
    "test2": {
      "action": "padding_oracle",
      "arguments": {
        "hostname": "localhost",
        "port": 18652,
        "key_id": 1234,
        "iv": "obLD1OX2BxgpOEdWobLD1A==",
        "ciphertext": "EFMvEYbUdZ49cd6wS8dqxZAY7Ix2HO6rYRupcF6qGzmk9HLAq1lIPi07UvEdwYHC"
      }
    },
    "test3": {
      "action": "padding_oracle",
      "arguments": {
        "hostname": "localhost",
        "port": 18652,
        "key_id": 1111,
        "iv": "ESIzRFVmd4iZAKq7zN3u/w==",
        "ciphertext": "+22EENNgvOX3ht/oYVu/Xg=="
      }
    }
  },
  "expectedResults": {
    "test1": {
      "plaintext": "VHQgbG9uZyBsdwYGBgYGBg=="
    },
    "test2": {
      "plaintext": "SGVsbG8gV29ycnJycnJycnIgdGVzdCB0ZXN0IHRlc3QQEBAQEBAQEBAQEBAQEBAQ"
    },
    "test3": {
      "plaintext": "U2hvcnQgbW1tBwcHBwcHBw=="
    }
  }
}

=== Sarsum/TINF23CS-kauma-tests/tests/03_action_gfpoly_sqrt_edgecases.json
{
  "title": "gfpoly_sqrt edgecases",
  "description": "",
  "authors": ["tametsi"],
  "testcases": {
    "8Z7CJ3uZ2J5j18AsqJcgl": {
      "action": "gfpoly_sqrt",
      "arguments": {
        "S": [
          "AAAAAAAAAAAAAAAAAAAAAA==",
          "AAAAAAAAAAAAAAAAAAAAAA==",
          "AAAAAAAAAAAAAAAAAAAAAA==",
          "AAAAAAAAAAAAAAAAAAAAAA==",
          "PKUa1+JHTxHE8y3LbuKIIA==",
          "AAAAAAAAAAAAAAAAAAAAAA==",
          "Ds96KiAKKoigKoiKiiKAiA=="
        ],
        "poly": "p1"
      }
    },
    "OIOBRatHMZRz9aqqavzg2": {
      "action": "gfpoly_sqrt",
      "arguments": {
        "S": ["5TxUxLHO1lHE/rSFquKIAg=="],
        "poly": "p1"
      }
    },
    "pzcsn7nCQrraNX68c14oc": {
      "action": "gfpoly_sqrt",
      "arguments": {
        "S": ["AAAAAAAAAAAAAAAAAAAAAA=="],
        "poly": "p1"
      }
    },
    "yJimdti2nIAHEnyxYyrF0": {
      "action": "gfpoly_sqrt",
      "arguments": {
        "S": ["gAAAAAAAAAAAAAAAAAAAAA=="],
        "poly": "p1"
      }
    }
  },
  "expectedResults": {
    "8Z7CJ3uZ2J5j18AsqJcgl": {
      "R": [
        "AAAAAAAAAAAAAAAAAAAAAA==",
        "AAAAAAAAAAAAAAAAAAAAAA==",
        "NeverGonnaRunAroundAAA==",
        "AndDesertYouAAAAAAAAAA=="
      ]
    },
    "OIOBRatHMZRz9aqqavzg2": {
      "R": ["NeverGonnaGiveYouUpAAA=="]
    },
    "pzcsn7nCQrraNX68c14oc": {
      "R": ["AAAAAAAAAAAAAAAAAAAAAA=="]
    },
    "yJimdti2nIAHEnyxYyrF0": {
      "R": ["gAAAAAAAAAAAAAAAAAAAAA=="]
    }
  }
}

=== Sarsum/TINF23CS-kauma-tests/tests/04_action_rsa_factor_edgecases.json
{
    "title": "rsa_factor action edgecases",
    "description": "01: one modul shares both factors with other moduli (and contains one random modul); 02: moduli (6) which shares both factors (2, 3) with moduli (10, 21) with again have both two shared factors (2,5),(3,7) with additional factors; 03: circular shared factors",
    "authors": [
        "Sarsum"
    ],
    "testcases": {
        "shared_factors_01": {
            "action": "rsa_factor",
            "arguments": {
                "moduli": [
                    323,
                    15,
                    391,
                    667
                ]
            }
        },
        "shared_factors_02": {
            "action": "rsa_factor",
            "arguments": {
                "moduli": [
                    6,
                    10,
                    21,
                    77,
                    65
                ]
            }
        },
        "shared_factors_03": {
            "action": "rsa_factor",
            "arguments": {
                "moduli": [
                    6,
                    10,
                    15
                ]
            }
        }
    },
    "expectedResults": {
        "shared_factors_01": {
            "factored_moduli": [
                [
                    17,
                    19
                ],
                [
                    17,
                    23
                ],
                [
                    23,
                    29
                ]
            ]
        },
        "shared_factors_02": {
            "factored_moduli": [
                [
                    2,
                    3
                ],
                [
                    2,
                    5
                ],
                [
                    3,
                    7
                ],
                [
                    5,
                    13
                ],
                [
                    7,
                    11
                ]
            ]
        },
        "shared_factors_03": {
            "factored_moduli": [
                [
                    2,
                    3
                ],
                [
                    2,
                    5
                ],
                [
                    3,
                    5
                ]
            ]
        }
    }
}

=== Sarsum/TINF23CS-kauma-tests/tests/action_padding_oracle.json
{
  "title": "Some padding oracle cases",
  "description": "Padding oracle test cases running on a hosted padding oracle server",
  "authors": ["melo-afk", "niri81"],
  "testcases": {
    "case9": {
      "action": "padding_oracle",
      "arguments": {
        "hostname": "kauma.melo.run",
        "port": 42424,
        "key_id": 46142,
        "iv": "ddCy7rA7gwwY5LKmv/NNeQ==",
        "ciphertext": "3QjuQ6pka3xvh7Fj+SJEUq+bOGJny8M0xucUKSVaa9Q="
      }
    },
    "case4": {
      "action": "padding_oracle",
      "arguments": {
        "hostname": "kauma.melo.run",
        "port": 42424,
        "key_id": 47244,
        "iv": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ciphertext": "GUwb/KeiSSdirCxg6Gq/zWBy6c/JiEM29qPRmQFKrzJkeF2qT8A5mnhyfM6pp1o31XsZzFHUrdlGH2vbxRbSYw=="
      }
    },
    "case5": {
      "action": "padding_oracle",
      "arguments": {
        "hostname": "kauma.melo.run",
        "port": 42424,
        "key_id": 46985,
        "iv": "Okje73DhcO7pHuxb9eUsbA==",
        "ciphertext": "BurVA/24D+bgj1nXzDAQQrH5S+jQ1AJeOwI+FrBW5kA="
      }
    },
    "case0": {
      "action": "padding_oracle",
      "arguments": {
        "hostname": "kauma.melo.run",
        "port": 42424,
        "key_id": 36269,
        "iv": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ciphertext": "74g9WIEG3/sWtjF1VeUv4w=="
      }
    },
    "case3": {
      "action": "padding_oracle",
      "arguments": {
        "hostname": "kauma.melo.run",
        "port": 42424,
        "key_id": 17306,
        "iv": "6uLkWl8Z8KfnXD4Rv2zEdg==",
        "ciphertext": "LxORmpPdzXNA7q668R5ZrCXK71r0GSv/izlrgQUa62E="
      }
    },
    "case6": {
      "action": "padding_oracle",
      "arguments": {
        "hostname": "kauma.melo.run",
        "port": 42424,
        "key_id": 32928,
        "iv": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ciphertext": "abdnrmU2/D/6axvrW5QLNH/qb1NaDwa/DzXf8ltVArQJZs972gdJDPxJHcscECAm"
      }
    },
    "case2": {
      "action": "padding_oracle",
      "arguments": {
        "hostname": "kauma.melo.run",
        "port": 42424,
        "key_id": 61992,
        "iv": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ciphertext": "TD8BL1HiazPRWsUb4lFqKYBuajXFcU1Dpmsxub9/DnQ="
      }
    },
    "case7": {
      "action": "padding_oracle",
      "arguments": {
        "hostname": "kauma.melo.run",
        "port": 42424,
        "key_id": 10853,
        "iv": "Cc5ybKcty92UgZs5964phg==",
        "ciphertext": "zNPD/2iDlvGFHzspE6v5sw=="
      }
    },
    "case8": {
      "action": "padding_oracle",
      "arguments": {
        "hostname": "kauma.melo.run",
        "port": 42424,
        "key_id": 19682,
        "iv": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ciphertext": "FzIDtvPqDm/S6MfyjooKlveCXiX3egEKuVLpMZUgfH8f9qxd0kMucbPfxOtbDFy+"
      }
    },
    "case1": {
      "action": "padding_oracle",
      "arguments": {
        "hostname": "kauma.melo.run",
        "port": 42424,
        "key_id": 3421,
        "iv": "HLfWD7uVBSkSrumLERmB4Q==",
        "ciphertext": "KlxGRFFRUaxtZDQKMQEKkndNwiWX2ajz76cRWzVAruM="
      }
    },
    "case10": {
      "action": "padding_oracle",
      "arguments": {
        "hostname": "kauma.melo.run",
        "port": 42424,
        "key_id": 52533,
        "iv": "oHsS7nnYMw8i3KqIzgfUww==",
        "ciphertext": "1RbM4Z9tPkxM8On5N7UiBOHmcVVKtdmGtIRFmQnk114SIPLm3XXZrK4xR8B3cE0++CTju82swUWe1c764iFOLw=="
      }
    }
  },
  "expectedResults": {
    "case7": {
      "plaintext": "dG8gbG92ZQkJCQkJCQkJCQ=="
    },
    "case9": {
      "plaintext": "WW91IGtub3cgdGhlIHJ1bGVzIGFuZCBzbyBkbyBJAgI="
    },
    "case0": {
      "plaintext": "dG8gbG92ZQAAAAAAAAACAQ=="
    },
    "case4": {
      "plaintext": "TmV2ZXIgZ29ubmEgZ2kCASB5b3UgdXAsIG5ldmVyIGdvbm5hIGxldCB5b3UgZG93bgAAAAAAAAAAAAAAAAAAAQ=="
    },
    "case1": {
      "plaintext": "WW91IGtub3cgdGhlIHJ1bGVzIGFuZCBzbyBkbyBJAgI="
    },
    "case6": {
      "plaintext": "TmV2ZXIgZ29ubmEgcnUCAWFyb3VuZCBhbmQgZGVzZXJ0IHlvdQAAAAAAAAAAAAAB"
    },
    "case5": {
      "plaintext": "V2UncmUgbm8gc3RyYW5nZXJzDg4ODg4ODg4ODg4ODg4="
    },
    "case8": {
      "plaintext": "WW91IHdvdWxkbid0IGcCASB0aGlzIGZyb20gYW55IG90aGVyIGd1eQAAAAAAAAAB"
    },
    "case2": {
      "plaintext": "V2UncmUgbm8gc3RyYW4CAXJzAAAAAAAAAAAAAAAAAAE="
    },
    "case3": {
      "plaintext": "WW91IGtub3cgdGhlIHJ1bGVzIGFuZCBzbyBkbyBJAgI="
    },
    "case10": {
      "plaintext": "TmV2ZXIgZ29ubmEgZ2l2ZSB5b3UgdXAsIG5ldmVyIGdvbm5hIGxldCB5b3UgZG93bg8PDw8PDw8PDw8PDw8PDw=="
    }
  }
}

=== Sarsum/TINF23CS-kauma-tests/tests/03_action_gfpoly_add_edgecases.json
{
    "title": "gfpoly_add edgecases",
    "description": "",
    "authors": [
        "Sarsum"
    ],
    "testcases": {
        "edge01": {
            "action": "gfpoly_add",
            "arguments": {
                "A": [
                    "gAAAAAAAAAAAAAAAAAAAAA=="
                ],
                "B": [
                    "gAAAAAAAAAAAAAAAAAAAAA=="
                ],
                "poly": "p1"
            }
        },
        "edge02": {
            "action": "gfpoly_add",
            "arguments": {
                "A": [
                    "gAAAAAAAAAAAAAAAAAAAAA==",
                    "gAAAAAAAAAAAAAAAAAAAAA=="
                ],
                "B": [
                    "gAAAAAAAAAAAAAAAAAAAAA==",
                    "gAAAAAAAAAAAAAAAAAAAAA=="
                ],
                "poly": "p1"
            }
        }
    },
    "expectedResults": {
        "edge01": {
            "S": [
                "AAAAAAAAAAAAAAAAAAAAAA=="
            ]
        },
        "edge02": {
            "S": [
                "AAAAAAAAAAAAAAAAAAAAAA=="
            ]
        }
    }
}

=== Sarsum/TINF23CS-kauma-tests/tests/02_action_gf_ops_02.json
{
    "title": "GF action custom testcases",
    "description": "Basic GF operations to test functionality",
    "testcases": {
        "case1": {
            "action": "gf_mul",
            "arguments": {
                "a": "AAAAAAAAAAAAAAAAAAAAAA==",
                "b": "AAAAAAAAAAAAAAAAAAAAAA==",
                "poly": "p1"
            }
        },
        "case2": {
            "action": "gf_mul",
            "arguments": {
                "a": "hAAAAEAAAAAAAAAAAAAAAA==",
                "b": "AAAAAAAAAAAAAAAAAAAAAA==",
                "poly": "p1"
            }
        },
        "case3": {
          "action": "gf_mul",
          "arguments": {
                "a": "hAAAAEAAAAAAAAAAAAAAAA==",
                "b": "AAAAAAAAAAAAAAAAAAAAAQ==",
                "poly": "p1"
            }
        },
        "case4": {
            "action": "gf_mul",
            "arguments": {
                "a": "QAAAAEAAAAAAAAAAAAAAAA==",
                "b": "QAAAAAAAAAAAAAAAAAAAAA==",
                "poly": "p1"
          }
        }
    },
    "expectedResults": {
        "case1": {
          "y": "AAAAAAAAAAAAAAAAAAAAAA=="
        },
        "case2": {
          "y": "AAAAAAAAAAAAAAAAAAAAAA=="
        },
        "case3": {
          "y": "DhAAAOEAAAAAAAAAAAAAAQ=="
        },
        "case4": {
          "y": "IAAAACAAAAAAAAAAAAAAAA=="
        }
    }
}
