=== Sarsum/TINF23CS-kauma-tests/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://raw.githubusercontent.com/sarsum/TINF23CS-kauma-tests/refs/heads/main/schema.json",
  "title": "Test Vectors",
  "description": "Test Vector including input and expected result to test the kauma application",
  "additionalProperties": false,
  "properties": {
    "title": { "type": "string" },
    "description": { "type": "string" },
    "authors": { "type": "array", "items": { "type": "string" } },
    "testcases": {
      "type": "object",
      "minProperties": 1,
      "description": "Map of testcase name -> testcase",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "action": { "type": "string" },
          "arguments": {
            "type": "object"
          }
        },
        "required": ["action", "arguments"]
      }
    },
    "expectedResults": {
        "type": "object",
        "properties": {
            "responses": {
                "minProperties": 1,
                "description": "Results of testcases. Sometimes for each testcase a result, sometimes one result computed by multiple actions.",
                "additionalProperties": {
                  "type": ["object", "null"]
                }
            }
        }
    }
  },
  "required": ["title", "description", "testcases", "expectedResults"]
}

=== Sarsum/TINF23CS-kauma-tests/tests/04_action_rsa_factor.json
{
    "title": "rsa_factor testcase from exercise sheet",
    "description": "The only default testcase",
    "testcases": {
        "default": {
            "action": "rsa_factor",
            "arguments": {
                "moduli": [
                    15,
                    221,
                    77,
                    1313
                ]
            }
        }
    },
    "expectedResults": {
        "default": {
            "factored_moduli": [
                [
                    13,
                    17
                ],
                [
                    13,
                    101
                ]
            ]
        }
    }
}
