=== Sarsum/TINF23CS-kauma-tests/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://raw.githubusercontent.com/sarsum/TINF23CS-kauma-tests/refs/heads/main/schema.json",
  "title": "Test Vectors",
  "description": "Test Vector including input and expected result to test the kauma application",
  "additionalProperties": false,
  "properties": {
    "title": { "type": "string" },
    "description": { "type": "string" },
    "authors": { "type": "array", "items": { "type": "string" } },
    "testcases": {
      "type": "object",
      "minProperties": 1,
      "description": "Map of testcase name -> testcase",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "action": { "type": "string" },
          "arguments": {
            "type": "object"
          }
        },
        "required": ["action", "arguments"]
      }
    },
    "expectedResults": {
        "type": "object",
        "properties": {
            "responses": {
                "minProperties": 1,
                "description": "Results of testcases. Sometimes for each testcase a result, sometimes one result computed by multiple actions.",
                "additionalProperties": {
                  "type": ["object", "null"]
                }
            }
        }
    }
  },
  "required": ["title", "description", "testcases", "expectedResults"]
}

=== Sarsum/TINF23CS-kauma-tests/tests/03_action_gcm_crack_00.json
{
  "title": "GCM crack test case",
  "description": "The gcm crack action example from the exercise sheet",
  "testcases": {
    "default_gcm_crack": {
      "action": "gcm_crack",
      "arguments": {
        "nonce": "4gF+BtR3ku/PUQci",
        "m1": {
          "ciphertext": "CGOkZDnJEt24aVV8mqQq+P4pouVDWhAYj0SN5MDAgg==",
          "associated_data": "TmFjaHJpY2h0IDE=",
          "tag": "GC9neV3aZLnmznTIWqCC4A=="
        },
        "m2": {
          "ciphertext": "FnWyLSTfRrO8Y1MuhLIs6A==",
          "associated_data": "",
          "tag": "gb2ph1vzwU85/FsUg51t3Q=="
        },
        "m3": {
          "ciphertext": "CGOkZDnJEt25aV58iaMt6O8+8chKVh0Eg1XFxA==",
          "associated_data": "TmFjaHJpY2h0IDM=",
          "tag": "+/aDjsAzTseDLuM4jt5Q6Q=="
        },
        "forgery": {
          "ciphertext": "AXe/ZQ==",
          "associated_data": ""
        },
        "poly": "p1"
      }
    }
  },
  "expectedResults": {
    "default_gcm_crack": {
      "tag": "Y16EEEO1sgJX3IsJSwEXlA==",
      "H": "Nxn7h7ruk8eiNAG6AfhUFg==",
      "mask": "tXjFK5vCqIPl6fKAJAyy9A=="
    }
  }
}

=== Sarsum/TINF23CS-kauma-tests/tests/action_calc.json
{
  "title": "Calc Action tests",
  "description": "Test vectors for the kauma calc action, including invalid actions and formats for calc.",
  "testcases": {
    "test1": {
      "action": "calc",
      "arguments": {
        "lhs": 123,
        "op": "+",
        "rhs": 234
      }
    },
    "test2": {
      "action": "calc",
      "arguments": {
        "lhs": 1234,
        "op": "*",
        "rhs": 333
      }
    },
    "test3": {
      "action": "calc",
      "arguments": {
        "lhs": 1000,
        "op": "/",
        "rhs": 3
      }
    },
    "test4": {
      "action": "calc",
      "arguments": {
        "lhs": "0x7fffffff",
        "op": "+",
        "rhs": 1
      }
    },
    "test5": {
      "action": "calc",
      "arguments": {
        "lhs": "-0xff",
        "op": "*",
        "rhs": 1000000
      }
    },
    "test6": {
      "action": "calc",
      "arguments": {
        "lhs": "-0xff",
        "op": "*"
      }
    },
    "test7": {
      "action": "calc",
      "arguments": {
        "op": "*",
        "rhs": 1000000
      }
    },
    "test8": {
      "action": "calc",
      "arguments": {
        "rhs": 1000000
      }
    },
    "test9": {
      "action": "clc",
      "arguments": {
        "lhs": 123,
        "op": "+",
        "rhs": 234
      }
    },
    "test10": {
      "action": "clc",
      "arguments": {
        "lhs": 123,
        "op": "/",
        "rhs": 0
      }
    }
  },
  "expectedResults": {
    "test1": {
      "answer": 357
    },
    "test2": {
      "answer": 410922
    },
    "test3": {
      "answer": 333
    },
    "test4": {
      "answer": "0x80000000"
    },
    "test5": {
      "answer": -255000000
    },
    "test6": null,
    "test7": null,
    "test8": null,
    "test9": null,
    "test10":null
  }
}

=== Sarsum/TINF23CS-kauma-tests/tests/03_action_gfpoly_factor_edf_edgecases.json
{
    "title": "gfpoly_factor_edf edgecases",
    "description": "This testcase specifically requires a random polynomial of length 2 and I somehow messed that up and used the degree as length input",
    "authors": ["Sarsum"],
    "testcases": {
        "edge01": {
            "action": "gfpoly_factor_edf",
            "arguments": {
                "F": [
                    "4Ry4HKU7/ELJGyP79XrSFg==",
                    "Ke5wrLTKZbKzJU3wwWDjaA==",
                    "gAAAAAAAAAAAAAAAAAAAAA=="
                ],
                "d": 1,
                "poly": "p1"
            }
        }
    },
    "expectedResults": {
        "edge01": {
            "factors": [
                [
                    "Bg1eynlbKljuAq+xEPzEdA==",
                    "gAAAAAAAAAAAAAAAAAAAAA=="
                ],
                [
                    "L+MuZs2RT+pdJ+JB0ZwnHA==",
                    "gAAAAAAAAAAAAAAAAAAAAA=="
                ]
            ]
        }
    }
}

=== Sarsum/TINF23CS-kauma-tests/tests/03_action_gfpoly_factor_ddf_p1_01.json
{
    "title": "Action gfpoly_factor_ddf testcase",
    "description": "random F values have been used",
    "authors": ["halotsch"],
    "testcases": {
    "case0": {
      "action": "gfpoly_factor_ddf",
      "arguments": {
        "F": [
          "tpkgAAAAAAAAAAAAAAAAAA==",
          "m6MQAAAAAAAAAAAAAAAAAA==",
          "8roAAAAAAAAAAAAAAAAAAA==",
          "3dUAAAAAAAAAAAAAAAAAAA==",
          "FwAAAAAAAAAAAAAAAAAAAA==",
          "/kAAAAAAAAAAAAAAAAAAAA==",
          "a4AAAAAAAAAAAAAAAAAAAA==",
          "gAAAAAAAAAAAAAAAAAAAAA=="
        ],
        "poly": "p1"
      }
    },
    "case1": {
      "action": "gfpoly_factor_ddf",
      "arguments": {
        "F": [
          "AQAAAAAAAAAAAAAAAAAAAA==",
          "gAAAAAAAAAAAAAAAAAAAAA=="
        ],
        "poly": "p1"
      }
    },
    "case2": {
      "action": "gfpoly_factor_ddf",
      "arguments": {
        "F": [
          "97bbbbbbbbbbbbbbbbbbbQ==",
          "LW2222222222222222222w==",
          "gAAAAAAAAAAAAAAAAAAAAA=="
        ],
        "poly": "p1"
      }
    }
  },
  "expectedResults": {
    "case0": {
      "factors": [
                {
          "factor": [
            "q4AAAAAAAAAAAAAAAAAAAA==",
            "gAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "degree": 1
        },
        {
          "factor": [
            "mmAAAAAAAAAAAAAAAAAAAA==",
            "AbAAAAAAAAAAAAAAAAAAAA==",
            "zgAAAAAAAAAAAAAAAAAAAA==",
            "FwAAAAAAAAAAAAAAAAAAAA==",
            "AAAAAAAAAAAAAAAAAAAAAA==",
            "wAAAAAAAAAAAAAAAAAAAAA==",
            "gAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "degree": 3
        }
      ]
    },
    "case1": {
      "factors": [
        {
          "factor": [
            "AQAAAAAAAAAAAAAAAAAAAA==",
            "gAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "degree": 1
        }
      ]
    },
    "case2": {
      "factors": [
        {
          "factor": [
            "97bbbbbbbbbbbbbbbbbbbQ==",
            "LW2222222222222222222w==",
            "gAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "degree": 1
        }
      ]
    }
  }
}

=== Sarsum/TINF23CS-kauma-tests/tests/03_action_gfpoly_sort_edgecases.json
{
    "title": "gfpoly_sort edgecases",
    "description": "",
    "authors": ["Sarsum"],
    "testcases": {
        "edge01": {
            "action": "gfpoly_sort",
            "arguments": {
                "polys": []
            }
        }
    },
    "expectedResults": {
        "edge01": {
            "sorted": []
        }
    }
}

=== Sarsum/TINF23CS-kauma-tests/tests/action_calc_03.json
{
  "title": "Calc Action Testcases",
  "description": "calc: integer representation and calculation (incl. division with negative operands)",
  "authors": ["tametsi"],
  "testcases": {
    "14MO7eegDIBbSA7BkfzmS": {
      "action": "calc",
      "arguments": { "lhs": 1, "op": "-", "rhs": -1 }
    },
    "4fZ-9sJJjRpjh6Iz_N_8L": {
      "action": "calc",
      "arguments": { "lhs": "0x80000000", "op": "+", "rhs": 1 }
    },
    "5LvUQgK1YMAznbI1agqxI": {
      "action": "calc",
      "arguments": { "lhs": 0, "op": "+", "rhs": 1 }
    },
    "9TlMcvYf8w949yqKKWILj": {
      "action": "calc",
      "arguments": { "lhs": 4, "op": "/", "rhs": 3 }
    },
    "Cqf2kFNcP1XUfOKwdtv0N": {
      "action": "calc",
      "arguments": { "lhs": 2, "op": "/", "rhs": 2 }
    },
    "Dnh45DpUyJd4oqz5JDe33": {
      "action": "calc",
      "arguments": { "lhs": -8, "op": "/", "rhs": 6 }
    },
    "DwwpV44P8uV3Lb1kzVgjf": {
      "action": "calc",
      "arguments": { "lhs": 8, "op": "/", "rhs": -6 }
    },
    "GvEN-C7wrGRNz63QVdH0A": {
      "action": "calc",
      "arguments": { "lhs": 4, "op": "/", "rhs": -3 }
    },
    "L7UkyKbbRyTibLIXcslyk": {
      "action": "calc",
      "arguments": { "lhs": 2, "op": "/", "rhs": 4 }
    },
    "LDV2REgooPOaa9WAXcRa0": {
      "action": "calc",
      "arguments": { "lhs": 1, "op": "-", "rhs": 0 }
    },
    "LSTjTYQ50QL0i9Qfu6aDU": {
      "action": "calc",
      "arguments": { "lhs": -4, "op": "/", "rhs": 3 }
    },
    "SscAnwKh3A9TImFmmCSGd": {
      "action": "calc",
      "arguments": { "lhs": 8, "op": "/", "rhs": -5 }
    },
    "cBL1k8St7WDLcWh4GliNM": {
      "action": "calc",
      "arguments": { "lhs": -8, "op": "/", "rhs": 3 }
    },
    "g6EkwXyYULQpogPbLLaf1": {
      "action": "calc",
      "arguments": { "lhs": 1, "op": "*", "rhs": -2 }
    },
    "galkF_WnOScUpAqK9x-tF": {
      "action": "calc",
      "arguments": { "lhs": 8, "op": "/", "rhs": -4 }
    },
    "kzGBBUV4C4cHiUKhH1fqZ": {
      "action": "calc",
      "arguments": { "lhs": 8, "op": "/", "rhs": -3 }
    },
    "lb8w2MtK9iq5w7LH_RG9B": {
      "action": "calc",
      "arguments": { "lhs": 2, "op": "*", "rhs": 2 }
    },
    "m9Zk_83opJaQzStCX_yVz": {
      "action": "calc",
      "arguments": { "lhs": 1, "op": "+", "rhs": -1 }
    },
    "puoZ2MqyfLtZKXHRMZj03": {
      "action": "calc",
      "arguments": { "lhs": "0xf09f92a9", "op": "*", "rhs": 1 }
    },
    "r32Kp7qTuwoj0xQupP-rD": {
      "action": "calc",
      "arguments": { "lhs": 4, "op": "/", "rhs": 2 }
    },
    "vCY8Q2rqJ7wWm6FEipYdD": {
      "action": "calc",
      "arguments": { "lhs": 8, "op": "/", "rhs": 6 }
    },
    "zJ692rBGGcAYQeYx4rx3j": {
      "action": "calc",
      "arguments": { "lhs": -8, "op": "/", "rhs": 5 }
    }
  },
  "expectedResults": {
    "14MO7eegDIBbSA7BkfzmS": { "answer": 2 },
    "4fZ-9sJJjRpjh6Iz_N_8L": { "answer": "0x80000001" },
    "5LvUQgK1YMAznbI1agqxI": { "answer": 1 },
    "9TlMcvYf8w949yqKKWILj": { "answer": 1 },
    "Cqf2kFNcP1XUfOKwdtv0N": { "answer": 1 },
    "Dnh45DpUyJd4oqz5JDe33": { "answer": -1 },
    "DwwpV44P8uV3Lb1kzVgjf": { "answer": -1 },
    "GvEN-C7wrGRNz63QVdH0A": { "answer": -1 },
    "L7UkyKbbRyTibLIXcslyk": { "answer": 0 },
    "LDV2REgooPOaa9WAXcRa0": { "answer": 1 },
    "LSTjTYQ50QL0i9Qfu6aDU": { "answer": -1 },
    "SscAnwKh3A9TImFmmCSGd": { "answer": -1 },
    "cBL1k8St7WDLcWh4GliNM": { "answer": -2 },
    "g6EkwXyYULQpogPbLLaf1": { "answer": -2 },
    "galkF_WnOScUpAqK9x-tF": { "answer": -2 },
    "kzGBBUV4C4cHiUKhH1fqZ": { "answer": -2 },
    "lb8w2MtK9iq5w7LH_RG9B": { "answer": 4 },
    "m9Zk_83opJaQzStCX_yVz": { "answer": 0 },
    "puoZ2MqyfLtZKXHRMZj03": { "answer": "0xf09f92a9" },
    "r32Kp7qTuwoj0xQupP-rD": { "answer": 2 },
    "vCY8Q2rqJ7wWm6FEipYdD": { "answer": 1 },
    "zJ692rBGGcAYQeYx4rx3j": { "answer": -1 }
  }
}

=== Sarsum/TINF23CS-kauma-tests/tests/02_action_gcm_encrypt.json
{
    "title": "AES GCM encryption test case",
    "description": "Default AES GCM encryption test case from exercise sheet",
    "testcases": {
        "default_gcm_encrypt": {
            "action": "gcm_encrypt",
            "arguments": {
                "poly": "p1",
                "nonce": "4gF+BtR3ku/PUQci",
                "key": "Xjq/GkpTSWoe3ZH0F+tjrQ==",
                "plaintext": "RGFzIGlzdCBlaW4gVGVzdA==",
                "ad": "QUQtRGF0ZW4="
            }
        }
    },
    "expectedResults": {
        "default_gcm_encrypt": {
            "ciphertext": "ET3RmvH/Hbuxba63EuPRrw==",
            "tag": "Mp0APJb/ZIURRwQlMgNN/w==",
            "L": "AAAAAAAAAEAAAAAAAAAAgA==",
            "H": "Bu6ywbsUKlpmZXMQyuGAng=="
        }
    }
}

=== Sarsum/TINF23CS-kauma-tests/tests/02_action_gf_ops.json
{
    "title": "GF action test cases",
    "description": "The galois field action examples from the exercise sheet",
    "testcases": {
        "default_gf_mul": {
            "action": "gf_mul",
            "arguments": {
                "a": "oAAAAEAAAAAAAAAAAAAAAA==",
                "b": "hAAAAAAAAAAAAAAAAAAAAA==",
                "poly": "p1"
            }
        },
        "default_gf_divmod": {
            "action": "gf_divmod",
            "arguments": {
                "a": "oAAAAEAAAAAAAAAAAAAAAA==",
                "b": "hAAAAAAAAAAAAAAAAAAAAA=="
            }
        },
        "default_gf_inv": {
            "action": "gf_inv",
            "arguments": {
                "x": "NeverGonnaGiveYouUp//w==",
                "poly": "p1"
            }
        },
        "default_gf_div": {
            "action": "gf_div",
            "arguments": {
                "a": "///YOUTUBE///////AAAAA==",
                "b": "///rS00xWnqwvI///AAAAA==",
                "poly": "p1"
            }
        },
        "default_gf_pow": {
            "action": "gf_pow",
            "arguments": {
                "b": "hAAAAAAAAAAAAAAAAAAAAA==",
                "e": 123456,
                "poly": "p1"
            }
        },
        "default_gf_sqrt": {
            "action": "gf_sqrt",
            "arguments": {
                "x": "oAAAAEAAAAAAAAAAAAAAAA==",
                "poly": "p2"
            }
        }
    },
    "expectedResults": {
        "default_gf_mul": { "y": "pQAAAEIAAAAAAAAAAAAAAA==" },
        "default_gf_divmod": {
            "q": "EIQhCAAAAAAAAAAAAAAAAA==",
            "r": "sAAAAAAAAAAAAAAAAAAAAA=="
        },
        "default_gf_inv": { "y": "NSrMarB2n+4IF8VXhrbSoQ==" },
        "default_gf_div": { "q": "KB8FyvjLM0AKY+f8BPNAEQ==" },
        "default_gf_pow": { "y": "Rp4NuH4f6V1sN4t51tkC7Q==" },
        "default_gf_sqrt": { "y": "vODfOEm+Mm8LfMTfDg/zgw==" }
    }
}
